variables:
  SSH_CONFIG: >
    Host server
      HostName chess.8086.cf
      User chess
      IdentityFile ~/.ssh/key
      StrictHostKeyChecking no

  DEPLOY_PATH: /var/www/chess.8086.cf

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - build-engine
  - build-app
  - deploy-app

build-engine-wasm:
  stage: build-engine
  image: emscripten/emsdk:2.0.18
  script:
    - export EM_CACHE=$PWD/emscripten-cache
    - mkdir -p "$EM_CACHE"
    - mkdir engine-wasm
    - cd engine
    - make -j$(nproc) ARCH=wasm clean build
    - mv royal100.{js,wasm,worker.js} ../engine-wasm/
  artifacts:
    expire_in: 1 hour
    paths:
      - engine-wasm
  cache:
    key: engine-wasm-${CI_COMMIT_REF_SLUG}
    paths:
      - emscripten-cache

build-app-browser:
  stage: build-app
  image: node:lts
  needs:
    - build-engine-wasm
  script:
    - npm install -g pnpm
    - pnpm config set store-dir $PWD/.pnpm-store
    - cp -r engine-wasm/* chess-ui/public/engine/
    - cd chess-ui
    - pnpm install
    - pnpm build
  artifacts:
    expire_in: 1 hour
    paths:
      - chess-ui/build
  cache:
    key: browser-${CI_COMMIT_REF_SLUG}
    paths:
      - .pnpm-store/

deploy-app-browser:
  stage: deploy-app
  image: alpine
  needs:
    - build-app-browser
  script:
    - apk update
    - apk add brotli openssh-client rsync
    - cd chess-ui
    - find build/ -type f -exec brotli --best --keep '{}' +
    - mkdir -p ~/.ssh
    - echo "$SSH_DEPLOY_KEY" >~/.ssh/key
    - chmod 400 ~/.ssh/key
    - echo "$SSH_CONFIG" >~/.ssh/config
    - rsync
      --archive
      --itemize-changes
      --compress
      --delete-delay
      --delay-updates
      --checksum
      build/
      server:"$DEPLOY_PATH"/
