stages:
  - build-engine
  - build-app

build-engine:
  stage: build-engine
  image: burningdaylight/mingw-arch
  artifacts:
    expire_in: 1 hour
    paths:
      - engine-bin/
  script:
    - mkdir engine-bin/
    - cd engine/
    - make -j$(nproc) ARCH=x86-64 COMP=gcc clean build
    - mv royal100 ../engine-bin/
    - make -j$(nproc) ARCH=x86-64 COMP=mingw clean build
    - mv royal100.exe ../engine-bin/
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build-app:
  stage: build-app
  image: electronuserland/builder:wine
  script:
    - export ELECTRON_CACHE=$PWD/cache/electron
    - export ELECTRON_BUILDER_CACHE=$PWD/cache/electron-builder
    - mv engine-bin/* chess-ui/assets/bin/engine/
    - mkdir -p release/{linux,windows}
    - cd chess-ui/
    - yarn install
    - yarn package:all
    - mv release/*.tar.gz ../release/linux/
    - mv release/*.zip ../release/windows/
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - chess-ui/node_modules
      - cache/electron
      - cache/electron-builder
  artifacts:
    paths:
      - release/
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

